import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { getValidSessionByToken } from '../../database/sessions';
import { Travelpost } from '../../database/travelPosts';
import PostsForm from './PostsForm';

type Props = { searchParams: { returnTo?: string | string[] } };

export const metadata = {
  title: 'Posts Admin page',
  description: 'Generated by create next app',
};

export default async function TravelPostsAdmin() {
  const sessionTokenCookie = cookies().get('sessionToken');

  const session =
    sessionTokenCookie &&
    (await getValidSessionByToken(sessionTokenCookie.value));

  if (!session) redirect('/login?returnTo=/users-admin');

  const users = await Travelpost();

  return <PostsForm users={users} />;
}
