import Image from 'next/image';
import Link from 'next/link';
import { getTravelPosts } from '../../database/travelPosts';

export const metadata = {
  title: 'Travelpost page',
  description: 'Generated by create next app',
};

export default async function TravelPostsPage() {
  const travelposts = await getTravelPosts();

  if (!travelposts) {
    return <div>Loading...</div>; // or display an error message
  }

  return (
    <div>
      <h1>These are my travel posts</h1>

      {travelposts.map((travelpost) => {
        return (
          <div
            key={`travelpost-div-${travelpost.id}`}
            data-test-id={`travelpost-type-${travelpost}`}
          >
            {/* <Link href={`/travelposts/${travelpost.id}`}> */}
            <div>{travelpost.placeName}</div>
            <Image
              src={`/images/${travelpost}.png`} // Adjust the path or use a different method for generating image paths
              alt="travelpost"
              width={200}
              height={200}
            />
            {/* </Link> */}
          </div>
        );
      })}
    </div>
  );
}
