// import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import LogoutButton from './(auth)/logout/LogoutButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Home Page | Home Page',
    template: '%s | Hiking App',
  },
  description: 'Generated by create next app',
};
// Bu "children" applicationdaki hersey demek. Bütün dosyalar, bütün routlar vs.... ( layoutlarin genel durumu böyle)
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav>
            {/* normalde bu parantezlerde "a" kullaniyoruz. nexjs de böyle bir özellik var, yukaridaki import next/linkden , a yerine link yaziyoruz. böylelikle , sayfa load ederken daha hizli calisiyor */}
            <Link href="/">Home</Link>
            <Link href="/about">Top 10 Places</Link>

            <Link href="/details">Maps</Link>
          </nav>
        </div>

        <div>
          <Link href="/register">Register</Link>
          <Link href="/login">Login</Link>
          <LogoutButton />
        </div>

        {children}
      </body>
    </html>
  );
}
