import './globals.css';
// components/RootLayout.js
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Image from 'next/image';
import Link from 'next/link';
import { ReactNode } from 'react';
import Logo from '../app/public/images/logo.png';
import { getUserBySessionToken } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home page | UpLeveled', template: '%s | UpLeveled' },
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout(props: Props) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');
  const user =
    sessionToken && (await getUserBySessionToken(sessionToken.value));

  return (
    <html lang="en">
      <body className="bg-cupcake text-blue-500 p-4 mx-auto">
        <nav className="bg-blue-500 p-4 text-white">
          <div className="container mx-auto flex justify-between items-center">
            {/* Use passHref prop and wrap the entire content in an anchor tag */}
            <Link href="/" passHref>
              <div className="cursor-pointer">
                {/* Use the Image component for better performance */}
                <Image src={Logo} alt="Logo" width={120} height={40} />
              </div>
            </Link>

            <div>
              <Link href="/travelPost" className="text-white ml-4">
                Travelposts
              </Link>
              <Link href="/notes" className="text-white ml-4">
                Check Notes
              </Link>
              <Link href="/posts" className="text-white ml-4">
                Posts
              </Link>

              {/* Rest of your navigation links */}
            </div>

            <div>
              {user ? (
                <>
                  <div className="text-white">{user.username}</div>
                  <LogoutButton />
                </>
              ) : (
                <>
                  <Link href="/register" className="text-white ml-4">
                    Register
                  </Link>
                  <Link href="/login" className="text-white ml-4">
                    Login
                  </Link>
                </>
              )}
            </div>
          </div>
        </nav>

        {props.children}
      </body>
    </html>
  );
}
